[project]
name = "tupsar"
version = "0.1.0"
description = "Digitise newspaper scans to articles"
readme = "README.md"
authors = [
    { name = "Timothy Langer", email = "zeevox.dev@gamil.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-generativeai>=0.8.4",
    "pillow>=11.1.0",
    "pymupdf>=1.25.2",
    "python-dotenv>=1.0.1",
    "python-magic>=0.4.27",
    "pyyaml>=6.0.2",
    "rich-argparse>=1.6.0",
    "rich>=13.9.4",
    "azure-ai-documentintelligence>=1.0.0",
    "pyright>=1.1.393",
    "scikit-image>=0.25.1",
    "ijson>=3.3.0",
    "langchain-core>=0.3.34rc1",
    "langchain-anthropic>=0.3.5",
    "langchain-google-genai>=2.0.9",
]

[project.scripts]
tupsar = "tupsar:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "pre-commit>=4.1.0",
    "pyright>=1.1.393",
    "ruff>=0.9.4",
    "types-pyyaml>=6.0.12.20241230",
]

[tool.uv]
prerelease = "allow"

[tool.ruff.format]
preview = true

[tool.ruff.lint]
preview = true

# Enable all the rules
select = ["ALL"]
fixable = ["ALL"]

ignore = [
    # Disable pydoclint rules, since they do not support Sphinx docstrings
    # see https://github.com/astral-sh/ruff/issues/12434
    "DOC",

    # Disable copyright header check
    "CPY",

    "D203", # prefer D211
    "D212", # prefer D213
    "COM812", # unnecessary rule
]

[tool.pyright]
venvPath = "."
venv = ".venv"
strict = ["src/tupsar/model", "src/tupsar/cli"]

[tool.mypy]
# Avoid type-checking untyped libraries
ignore_missing_imports = true
# Use strict mode
strict = true
